<?php

namespace Proxies\__CG__\Frontend\Bundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Ciudad extends \Frontend\Bundle\Entity\Ciudad implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getPosicion()
    {
        $this->__load();
        return parent::getPosicion();
    }

    public function setPosicion($posicion)
    {
        $this->__load();
        return parent::setPosicion($posicion);
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNombreCiudad($nombreCiudad)
    {
        $this->__load();
        return parent::setNombreCiudad($nombreCiudad);
    }

    public function getNombreCiudad()
    {
        $this->__load();
        return parent::getNombreCiudad();
    }

    public function setProvinciaPk(\Frontend\Bundle\Entity\Provincia $provinciaPk = NULL)
    {
        $this->__load();
        return parent::setProvinciaPk($provinciaPk);
    }

    public function getProvinciaPk()
    {
        $this->__load();
        return parent::getProvinciaPk();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function getCiudadPais()
    {
        $this->__load();
        return parent::getCiudadPais();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nombreCiudad', 'posicion', 'provinciaPk');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}