<?php

namespace Proxies\__CG__\Frontend\Bundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Producto extends \Frontend\Bundle\Entity\Producto implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getFechaModificacion()
    {
        $this->__load();
        return parent::getFechaModificacion();
    }

    public function setFechaModificacion(\DateTime $fechaModificacion)
    {
        $this->__load();
        return parent::setFechaModificacion($fechaModificacion);
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNombreImagen($nombreImagen)
    {
        $this->__load();
        return parent::setNombreImagen($nombreImagen);
    }

    public function getNombreImagen()
    {
        $this->__load();
        return parent::getNombreImagen();
    }

    public function setImagenExtension($imagenExtension)
    {
        $this->__load();
        return parent::setImagenExtension($imagenExtension);
    }

    public function getImagenExtension()
    {
        $this->__load();
        return parent::getImagenExtension();
    }

    public function setImagen(\Symfony\Component\HttpFoundation\File\UploadedFile $imagen = NULL)
    {
        $this->__load();
        return parent::setImagen($imagen);
    }

    public function getImagen()
    {
        $this->__load();
        return parent::getImagen();
    }

    public function setCategoriaPk(\Frontend\Bundle\Entity\Categoria $categoriaPk = NULL)
    {
        $this->__load();
        return parent::setCategoriaPk($categoriaPk);
    }

    public function getCategoriaPk()
    {
        $this->__load();
        return parent::getCategoriaPk();
    }

    public function setFiguraPk(\Frontend\Bundle\Entity\Figura $figuraPk = NULL)
    {
        $this->__load();
        return parent::setFiguraPk($figuraPk);
    }

    public function getFiguraPk()
    {
        $this->__load();
        return parent::getFiguraPk();
    }

    public function upload()
    {
        $this->__load();
        return parent::upload();
    }

    public function preUpload()
    {
        $this->__load();
        return parent::preUpload();
    }

    public function storeFilenameForRemove()
    {
        $this->__load();
        return parent::storeFilenameForRemove();
    }

    public function removeUpload()
    {
        $this->__load();
        return parent::removeUpload();
    }

    public function getAbsolutePath()
    {
        $this->__load();
        return parent::getAbsolutePath();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function getPosicion()
    {
        $this->__load();
        return parent::getPosicion();
    }

    public function setPosicion($posicion)
    {
        $this->__load();
        return parent::setPosicion($posicion);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nombreImagen', 'imagenExtension', 'fechaModificacion', 'posicion', 'categoriaPk', 'figuraPk');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}