usuario:
    pattern:  /
    defaults: { _controller: "FrontendBundle:Usuario:new" }

usuario_create:
    pattern:  /crear
    defaults: { _controller: "FrontendBundle:Usuario:create" }
    requirements: { _method: post }

usuario_edit:
    pattern:  /{id}/editar
    defaults: { _controller: "FrontendBundle:Usuario:edit" }

usuario_update:
    pattern:  /{id}/actualizar
    defaults: { _controller: "FrontendBundle:Usuario:update" }
    requirements: { _method: post|put }

usuario_delete:
    pattern:  /{id}/eliminar
    defaults: { _controller: "FrontendBundle:Usuario:delete" }
