<?php

namespace Proxies\__CG__\Frontend\Bundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Pedido extends \Frontend\Bundle\Entity\Pedido implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getEtapa()
    {
        $this->__load();
        return parent::getEtapa();
    }

    public function setEtapa($etapa)
    {
        $this->__load();
        return parent::setEtapa($etapa);
    }

    public function getPedidoProducto()
    {
        $this->__load();
        return parent::getPedidoProducto();
    }

    public function getNumPedidoProducto()
    {
        $this->__load();
        return parent::getNumPedidoProducto();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getIdRecur()
    {
        $this->__load();
        return parent::getIdRecur();
    }

    public function setFechaRegistro($fechaRegistro)
    {
        $this->__load();
        return parent::setFechaRegistro($fechaRegistro);
    }

    public function getFechaRegistro()
    {
        $this->__load();
        return parent::getFechaRegistro();
    }

    public function setFechaActualizacion($fechaActualizacion)
    {
        $this->__load();
        return parent::setFechaActualizacion($fechaActualizacion);
    }

    public function getFechaActualizacion()
    {
        $this->__load();
        return parent::getFechaActualizacion();
    }

    public function setConceptoFactura($conceptoFactura)
    {
        $this->__load();
        return parent::setConceptoFactura($conceptoFactura);
    }

    public function getConceptoFactura()
    {
        $this->__load();
        return parent::getConceptoFactura();
    }

    public function setDescuento($descuento)
    {
        $this->__load();
        return parent::setDescuento($descuento);
    }

    public function getDescuento()
    {
        $this->__load();
        return parent::getDescuento();
    }

    public function setAplicaConcepto1($aplicaConcepto1)
    {
        $this->__load();
        return parent::setAplicaConcepto1($aplicaConcepto1);
    }

    public function getAplicaConcepto1()
    {
        $this->__load();
        return parent::getAplicaConcepto1();
    }

    public function setAplicaConcepto2($aplicaConcepto2)
    {
        $this->__load();
        return parent::setAplicaConcepto2($aplicaConcepto2);
    }

    public function getAplicaConcepto2()
    {
        $this->__load();
        return parent::getAplicaConcepto2();
    }

    public function setFechaAprobacion($fechaAprobacion)
    {
        $this->__load();
        return parent::setFechaAprobacion($fechaAprobacion);
    }

    public function getFechaAprobacion()
    {
        $this->__load();
        return parent::getFechaAprobacion();
    }

    public function setFechaMaximaEntrega($fechaMaximaEntrega)
    {
        $this->__load();
        return parent::setFechaMaximaEntrega($fechaMaximaEntrega);
    }

    public function getFechaMaximaEntrega()
    {
        $this->__load();
        return parent::getFechaMaximaEntrega();
    }

    public function setFinanciamiento($financiamiento)
    {
        $this->__load();
        return parent::setFinanciamiento($financiamiento);
    }

    public function getFinanciamiento()
    {
        $this->__load();
        return parent::getFinanciamiento();
    }

    public function setFacturaNum($facturaNum)
    {
        $this->__load();
        return parent::setFacturaNum($facturaNum);
    }

    public function getFacturaNum()
    {
        $this->__load();
        return parent::getFacturaNum();
    }

    public function setBanco($banco)
    {
        $this->__load();
        return parent::setBanco($banco);
    }

    public function getBanco()
    {
        $this->__load();
        return parent::getBanco();
    }

    public function setNotas($notas)
    {
        $this->__load();
        return parent::setNotas($notas);
    }

    public function getNotas()
    {
        $this->__load();
        return parent::getNotas();
    }

    public function setPaso1($paso1)
    {
        $this->__load();
        return parent::setPaso1($paso1);
    }

    public function getPaso1()
    {
        $this->__load();
        return parent::getPaso1();
    }

    public function setPaso2($paso2)
    {
        $this->__load();
        return parent::setPaso2($paso2);
    }

    public function getPaso2()
    {
        $this->__load();
        return parent::getPaso2();
    }

    public function setPaso3($paso3)
    {
        $this->__load();
        return parent::setPaso3($paso3);
    }

    public function getPaso3()
    {
        $this->__load();
        return parent::getPaso3();
    }

    public function setPaso4($paso4)
    {
        $this->__load();
        return parent::setPaso4($paso4);
    }

    public function getPaso4()
    {
        $this->__load();
        return parent::getPaso4();
    }

    public function setPaso5($paso5)
    {
        $this->__load();
        return parent::setPaso5($paso5);
    }

    public function getPaso5()
    {
        $this->__load();
        return parent::getPaso5();
    }

    public function setPaso6($paso6)
    {
        $this->__load();
        return parent::setPaso6($paso6);
    }

    public function getPaso6()
    {
        $this->__load();
        return parent::getPaso6();
    }

    public function setPaso7($paso7)
    {
        $this->__load();
        return parent::setPaso7($paso7);
    }

    public function getPaso7()
    {
        $this->__load();
        return parent::getPaso7();
    }

    public function setPaso8($paso8)
    {
        $this->__load();
        return parent::setPaso8($paso8);
    }

    public function getPaso8()
    {
        $this->__load();
        return parent::getPaso8();
    }

    public function setPaso9($paso9)
    {
        $this->__load();
        return parent::setPaso9($paso9);
    }

    public function getPaso9()
    {
        $this->__load();
        return parent::getPaso9();
    }

    public function setPaso10($paso10)
    {
        $this->__load();
        return parent::setPaso10($paso10);
    }

    public function getPaso10()
    {
        $this->__load();
        return parent::getPaso10();
    }

    public function setPaso11($paso11)
    {
        $this->__load();
        return parent::setPaso11($paso11);
    }

    public function getPaso11()
    {
        $this->__load();
        return parent::getPaso11();
    }

    public function setPaso12($paso12)
    {
        $this->__load();
        return parent::setPaso12($paso12);
    }

    public function getPaso12()
    {
        $this->__load();
        return parent::getPaso12();
    }

    public function setPaso13($paso13)
    {
        $this->__load();
        return parent::setPaso13($paso13);
    }

    public function getPaso13()
    {
        $this->__load();
        return parent::getPaso13();
    }

    public function setPaso14($paso14)
    {
        $this->__load();
        return parent::setPaso14($paso14);
    }

    public function getPaso14()
    {
        $this->__load();
        return parent::getPaso14();
    }

    public function setPaso15($paso15)
    {
        $this->__load();
        return parent::setPaso15($paso15);
    }

    public function getPaso15()
    {
        $this->__load();
        return parent::getPaso15();
    }

    public function setPaso16($paso16)
    {
        $this->__load();
        return parent::setPaso16($paso16);
    }

    public function getPaso16()
    {
        $this->__load();
        return parent::getPaso16();
    }

    public function setRetencionRenta($retencionRenta)
    {
        $this->__load();
        return parent::setRetencionRenta($retencionRenta);
    }

    public function getRetencionRenta()
    {
        $this->__load();
        return parent::getRetencionRenta();
    }

    public function setRetencionIva($retencionIva)
    {
        $this->__load();
        return parent::setRetencionIva($retencionIva);
    }

    public function getRetencionIva()
    {
        $this->__load();
        return parent::getRetencionIva();
    }

    public function setCoordinadorUsuarioPk(\Frontend\Bundle\Entity\Usuario $coordinadorUsuarioPk = NULL)
    {
        $this->__load();
        return parent::setCoordinadorUsuarioPk($coordinadorUsuarioPk);
    }

    public function getCoordinadorUsuarioPk()
    {
        $this->__load();
        return parent::getCoordinadorUsuarioPk();
    }

    public function setContactoPk(\Frontend\Bundle\Entity\Contacto $contactoPk = NULL)
    {
        $this->__load();
        return parent::setContactoPk($contactoPk);
    }

    public function getContactoPk()
    {
        $this->__load();
        return parent::getContactoPk();
    }

    public function setDelegado1UsuarioPk(\Frontend\Bundle\Entity\Usuario $delegado1UsuarioPk = NULL)
    {
        $this->__load();
        return parent::setDelegado1UsuarioPk($delegado1UsuarioPk);
    }

    public function getDelegado1UsuarioPk()
    {
        $this->__load();
        return parent::getDelegado1UsuarioPk();
    }

    public function setDelegado2UsuarioPk(\Frontend\Bundle\Entity\Usuario $delegado2UsuarioPk = NULL)
    {
        $this->__load();
        return parent::setDelegado2UsuarioPk($delegado2UsuarioPk);
    }

    public function getDelegado2UsuarioPk()
    {
        $this->__load();
        return parent::getDelegado2UsuarioPk();
    }

    public function setDelegado3UsuarioPk(\Frontend\Bundle\Entity\Usuario $delegado3UsuarioPk = NULL)
    {
        $this->__load();
        return parent::setDelegado3UsuarioPk($delegado3UsuarioPk);
    }

    public function getDelegado3UsuarioPk()
    {
        $this->__load();
        return parent::getDelegado3UsuarioPk();
    }

    public function setPasoPedidosPk(\Frontend\Bundle\Entity\PasoPedido $pasoPedidosPk = NULL)
    {
        $this->__load();
        return parent::setPasoPedidosPk($pasoPedidosPk);
    }

    public function getPasoPedidosPk()
    {
        $this->__load();
        return parent::getPasoPedidosPk();
    }

    public function setUltimaActualizacionUsuarioPk(\Frontend\Bundle\Entity\Usuario $ultimaActualizacionUsuarioPk = NULL)
    {
        $this->__load();
        return parent::setUltimaActualizacionUsuarioPk($ultimaActualizacionUsuarioPk);
    }

    public function getUltimaActualizacionUsuarioPk()
    {
        $this->__load();
        return parent::getUltimaActualizacionUsuarioPk();
    }

    public function addPedidoProducto(\Frontend\Bundle\Entity\PedidoProducto $pedidoProducto)
    {
        $this->__load();
        return parent::addPedidoProducto($pedidoProducto);
    }

    public function removePedidoProducto(\Frontend\Bundle\Entity\PedidoProducto $pedidoProducto)
    {
        $this->__load();
        return parent::removePedidoProducto($pedidoProducto);
    }

    public function removeTodosPedidoProducto()
    {
        $this->__load();
        return parent::removeTodosPedidoProducto();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function getFinalizado()
    {
        $this->__load();
        return parent::getFinalizado();
    }

    public function getSubtotalSinDescuento()
    {
        $this->__load();
        return parent::getSubtotalSinDescuento();
    }

    public function getTotalDescuento()
    {
        $this->__load();
        return parent::getTotalDescuento();
    }

    public function getCuota()
    {
        $this->__load();
        return parent::getCuota();
    }

    public function getIvaCuota()
    {
        $this->__load();
        return parent::getIvaCuota();
    }

    public function getTotalCuota()
    {
        $this->__load();
        return parent::getTotalCuota();
    }

    public function getSubtotal()
    {
        $this->__load();
        return parent::getSubtotal();
    }

    public function getIva()
    {
        $this->__load();
        return parent::getIva();
    }

    public function getTotal()
    {
        $this->__load();
        return parent::getTotal();
    }

    public function getRetencionRentaTotal()
    {
        $this->__load();
        return parent::getRetencionRentaTotal();
    }

    public function getRetencionIvaTotal()
    {
        $this->__load();
        return parent::getRetencionIvaTotal();
    }

    public function getLiquido()
    {
        $this->__load();
        return parent::getLiquido();
    }

    public function getRetenido()
    {
        $this->__load();
        return parent::getRetenido();
    }

    public function getChecks()
    {
        $this->__load();
        return parent::getChecks();
    }

    public function setPasoPorNum($num, $valor)
    {
        $this->__load();
        return parent::setPasoPorNum($num, $valor);
    }

    public function getPasoPorNum($num)
    {
        $this->__load();
        return parent::getPasoPorNum($num);
    }

    public function getNotasControl()
    {
        $this->__load();
        return parent::getNotasControl();
    }

    public function setNotasControl($notasControl)
    {
        $this->__load();
        return parent::setNotasControl($notasControl);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'fechaRegistro', 'fechaActualizacion', 'conceptoFactura', 'descuento', 'aplicaConcepto1', 'aplicaConcepto2', 'fechaAprobacion', 'fechaMaximaEntrega', 'financiamiento', 'facturaNum', 'banco', 'notas', 'notasControl', 'paso1', 'paso2', 'paso3', 'paso4', 'paso5', 'paso6', 'paso7', 'paso8', 'paso9', 'paso10', 'paso11', 'paso12', 'paso13', 'paso14', 'paso15', 'paso16', 'retencionRenta', 'retencionIva', 'etapa', 'coordinadorUsuarioPk', 'contactoPk', 'delegado1UsuarioPk', 'delegado2UsuarioPk', 'delegado3UsuarioPk', 'pasoPedidosPk', 'ultimaActualizacionUsuarioPk', 'pedidoProducto');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}